name: Update Credly badges

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    
jobs:
  update-readme:
    name: Update Readme with Credly badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: soeren-herrmann
          BADGE_SIZE: 100
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER_LAST_BADGES: 0 
