name: Update Credly badges

on:
  workflow_call:
    
jobs:
  update-readme:
    name: Update Readme with Credly badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: soeren-herrmann
          BADGE_SIZE: 100
