name: Update certifications

on:
    workflow_call:
    
jobs:
    update-readme-certifications:
        name: Update certifications
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          
          - name: Pull latest changes
            run: git pull origin main

          - name: List certification files
            run: |
              ls OtherCertifications > certifications.txt
              sed -i 's/ /__/g' certifications.txt
              sed -i 's/.pdf//g' certifications.txt
              sed -i '1d' certifications.txt
              cat certifications.txt
              # Clear existing certifications
              sed -i '/<!-- CERTIFICATIONS -->/,/<!-- END CERTIFICATIONS -->/d' README.md

              # Generate new badges and insert them
                while IFS= read -r cert; do
                echo "![Certification](https://img.shields.io/badge/Certification-$cert-brightgreen)"
                sed -i "/<!-- CERTIFICATIONS -->/i ![Certification](https://img.shields.io/badge/Certification-$cert-brightgreen)" README.md
                done < certifications.txt
                

          - name: Commit changes
            run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add README.md
              git commit -m 'Update certifications in README'
              git push origin main