name: Update certifications

on:
    workflow_call:
    
jobs:
    update-readme-certifications:
        name: Update certifications
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          
          - name: Pull latest changes
            run: git pull origin main

          - name: List certification files
            run: |
              ls OtherCertifications > certifications.txt

          - name: Generate badges
            run: |
              for cert in OtherCertifications/*; do
                cert_name=$(basename "$cert" | sed 's/_/ /g')
                echo "![Certification](https://img.shields.io/badge/Certification-$cert_name-brightgreen)" >> badges.txt
              done
              badges=$(cat badges.txt)
              badges=$(printf '%s\n' "$badges" | sed 's/[\/&]/\\&/g')
              sed -i '/<!-- CERTIFICATIONS -->/,/<!-- END CERTIFICATIONS -->/c\<!-- CERTIFICATIONS -->\n'"$badges"'\n<!-- END CERTIFICATIONS -->' README.md

          - name: Commit changes
            run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add README.md
              git commit -m 'Update certifications in README'
              git push origin main