name: Update certifications

on:
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: List certification files
            run: |
              ls OtherCertifications > certifications.txt

          - name: Generate badges
            run: |
              for cert in OtherCertifications/*; do
                cert_name=$(basename "$cert" | sed 's/_/ /g')
                echo "![Certification](https://img.shields.io/badge/Certification-$cert_name-brightgreen)" >> badges.txt
              done
              cat badges.txt

          - name: Update README
            run: |
              sed -i '/<!-- CERTIFICATIONS -->/,/<!-- END CERTIFICATIONS -->/d' README.md
              cat badges.txt >> README.md

          - name: Commit changes
            run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add README.md
              git commit -m 'Update certifications in README'

          - name: Push changes
            uses: ad-m/github-push-action@v0.6.0
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}