name: Update certifications

on:
    workflow_call:
    
jobs:
    update-readme-certifications:
        name: Update certifications
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          
          - name: Pull latest changes
            run: git pull origin main

          - name: List certification files
            run: |
              ls OtherCertifications > certifications.txt
              sed -i 's/ /__/g' certifications.txt
              sed -i 's/.pdf//g' certifications.txt
              sed -i '1d' certifications.txt

          - name: Generate badges
            run: |
                # Clear existing certifications
                sed -i '/<!-- CERTIFICATIONS -->/,/<!-- END CERTIFICATIONS -->/d' README.md

                # Generate new badges and insert them
                for cert in OtherCertifications/*; do
                  echo "![Certification](https://img.shields.io/badge/Certification-$cert_name-brightgreen)"
                  cert_name=$(basename "$cert" | sed 's/_/ /g')
                  sed -i "/<!-- CERTIFICATIONS -->/i ![Certification](https://img.shields.io/badge/Certification-$cert_name-brightgreen)" README.md
                done

          - name: Commit changes
            run: |
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'
              git add README.md
              git commit -m 'Update certifications in README'
              git push origin main