name: Main workflow

on: 
    push:
        branches:
            - main
jobs:
    call-credly:
        uses: ./.github/workflows/badges.yml
    call-certifications:
        needs: call-credly
        uses: ./.github/workflows/certifications.yml