name: Main workflow

on: 
    schedule:
        - cron: 0 0 * * *
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    call-credly:
        uses: ./.github/workflows/badges.yml
        secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
    call-certifications:
        needs: call-credly
        uses: ./.github/workflows/certifications.yml
    call-design-tools:
        needs: call-certifications
        uses: ./.github/workflows/tools.yml
